export const experienceLevel: string[] = [
  'Internship',
  'Entry Level',
  'Associate',
  'Junior Level',
  'Mid-Senior level',
  'Director',
  'Executive',
];

export const resumeType: string[] = [
  'Accounting',
  'Airlines',
  'Alternative Dispute Resolution',
  'Alternative Medicine',
  'Animation',
  'Apparel &amp; Fashion',
  'Architecture',
  'Arts',
  'Crafts',
  'Automotive',
  'Aviation',
  'Aerospace',
  'Banking',
  'Biotechnology',
  'Broadcast Media',
  'Building Materials',
  'Business Supplies &amp; Equipment',
  'Capital Markets',
  'Chemicals',
  'Social Organization',
  'Civil Engineering',
  'Network Security',
  'Games Development',
  'Hardware Engineering',
  'Network Engineering',
  'Software Development',
  'Construction',
  'Consumer Electronics',
  'Consumer Goods',
  'Consumer Services',
  'Cosmetics',
  'Dairy',
  'Defense &amp; Space',
  'Design',
  'Education Management',
  'Electronic Manufacturing',
  'Entertainment',
  'Environment',
  'Events',
  'Executive Office',
  'Facilities Services',
  'Agricultural',
  'Financial Services',
  'Fine Art',
  'Harvest',
  'Food &amp; Beverages',
  'Food Production',
  'Fundraising',
  'Furniture',
  'Government Administration',
  'Government Relations',
  'Graphic Design',
  'Health',
  'Wellness',
  'Fitness',
  'Education',
  'Health Care',
  'Hospital',
  'Hospitality',
  'Human Resources',
  'Import &amp; Export',
  'Individual Services',
  'Family Services',
  'Industrial Automation',
  'Information Services',
  'Information Technology &amp; Services',
  'Insurance',
  'International Affairs',
  'International Trade &amp; Development',
  'Internet',
  'Investment Banking',
  'Investment Management',
  'Justice',
  'Law Enforcement',
  'Law Practice',
  'Legal Services',
  'Legislative Office',
  'Travel &amp; Tourism',
  'Logistics',
  'Supply Chain',
  'Jewelry',
  'Luxury Goods',
  'Machinery',
  'Management Consulting',
  'Market Research',
  'Marketing',
  'Advertising',
  'Mechanical',
  'Industrial Engineering',
  'Media Production',
  'Medical Devices',
  'Medical Practice',
  'Mental Health Care',
  'Military',
  'Mining &amp; Metals',
  'Motion Pictures &amp; Film',
  'Museums',
  'Institutions',
  'Music',
  'Nanotechnology',
  'Newspapers',
  'Non Profit Organization Management',
  'Oil',
  'Energy',
  'Online Media',
  'Fulfillment',
  'Freight Delivery',
  'Packaging &amp; Containers',
  'Paper',
  'Forest',
  'Pharmaceuticals',
  'Photography',
  'Plastics',
  'Political Organization',
  'Printing',
  'Professional Training',
  'Coaching',
  'Program Development',
  'Public Policy',
  'Public Relations',
  'Communications',
  'Public Safety',
  'Publishing',
  'Real Estate',
  'Recreational Facilities',
  'Recreational Services',
  'Renewables',
  'Research',
  'Restaurants',
  'Retail',
  'Security',
  'Investigations',
  'Semiconductors',
  'Shipbuilding',
  'Sports',
  'Staffing &amp; Recruiting',
  'Telecommunications',
  'Think Tanks',
  'Tobacco',
  'Translation &amp; Localization',
  'Transportation',
  'Utilities',
  'Venture Capital',
  'Private Equity',
  'Veterinary',
  'Warehouse',
  'Wholesale',
  'Wireless',
  'Writing &amp; Editing',
];
