import Dashboard from '@/components/Dashboard/Dashboard';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Dashboard>{children}</Dashboard>
      {/* {children} */}
    </>
  );
}
